name: web configuration
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
        working-directory: client
      - name: build project
        run: npm run build:prod
        working-directory: client
      - name: linting typescript
        run: npm run lint:ts
        working-directory: client
      - name: linting css
        run: npm run lint:scss
        working-directory: client
      - name: unit testing
        run: npm run test:unit
        working-directory: client
